# Generated by Django 6.0.2 on 2026-02-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        ('lexicon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('min_months', models.PositiveSmallIntegerField()),
                ('max_months', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.ageband')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.centre')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.ageband')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.centre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('screening_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.screeningset')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexicon.word')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='screening.screeningsession')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'position'), name='uniq_screeningattempt_session_position')],
            },
        ),
        migrations.CreateModel(
            name='ScreeningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexicon.word')),
                ('screening_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='screening.screeningset')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('screening_set', 'position'), name='uniq_screeningitem_set_position')],
            },
        ),
    ]
