# Generated by Django 6.0.2 on 2026-02-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        ('lexicon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('DAILY', 'Daily practice'), ('REVIEW', 'Review practice'), ('SCREENING', 'Screening')], default='DAILY', max_length=16)),
                ('child_display_name', models.CharField(blank=True, max_length=100)),
                ('planned_item_count', models.PositiveSmallIntegerField(default=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.centre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexicon.word')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='practice.practicesession')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'position'), name='uniq_practiceitem_session_position')],
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexicon.word')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.practicesession')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'position'), name='uniq_practiceattempt_session_position')],
            },
        ),
    ]
