# Generated by Django 6.0.2 on 2026-02-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(blank=True, max_length=20)),
                ('jyutping', models.CharField(blank=True, max_length=50)),
                ('meaning', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('sound_group', models.CharField(choices=[('INITIAL', 'Initial consonant'), ('FINAL', 'Final consonant'), ('VOWEL', 'Vowel'), ('DIPHTHONG', 'Diphthong'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('hierarchy_stage', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('component_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='lexicon.word')),
                ('parent_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='lexicon.word')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('parent_word', 'position'), name='uniq_wordcomponent_parent_position')],
            },
        ),
    ]
